version: "3.9"

services:
  bot:
    container_name: telegram_bot
    build: .
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - default
      - postgre-sql-network

networks:
  default:
    external: true
    name: nginx_network
  postgre-sql-network:
    external: true
    name: postgre_sql_network
